export const seedState = {
  leadRecords: [
    {
      id: 'lead-001',
      name: 'Mia Torres',
      handle: '@miamoves',
      source: 'IG DM comment keyword',
      offer: 'Low-ticket challenge',
      stage: 'checkout-sent',
      owner: 'Alex',
      tags: ['dm-sprint', 'warm', 'challenge'],
      budget: '$49 low-ticket',
      nextAction: 'Wait 2h, then send urgency follow-up',
      lastTouch: '2 min ago',
    },
    {
      id: 'lead-002',
      name: 'Evan Ross',
      handle: '@evanbuilds',
      source: 'Story reply',
      offer: 'Consult call',
      stage: 'no-show',
      owner: 'Nina',
      tags: ['consult', 'no-show', 'high-intent'],
      budget: '$2.5k consult',
      nextAction: 'Send recovery voice note + reschedule link',
      lastTouch: '17 min ago',
    },
    {
      id: 'lead-003',
      name: 'Jade Porter',
      handle: '@jadeteaches',
      source: 'Lead form retargeting',
      offer: 'Subscription',
      stage: 'won',
      owner: 'Alex',
      tags: ['subscriber', 'upsell-ready'],
      budget: '$97 monthly',
      nextAction: 'Trigger onboarding autopilot',
      lastTouch: '31 min ago',
    },
  ],
  bookingRecords: [
    {
      id: 'book-001',
      leadId: 'lead-002',
      slot: 'Today, 2:30 PM',
      owner: 'Nina',
      status: 'no-show',
      recoveryAction: 'Voice note + reschedule link queued for 15 min delay',
    },
    {
      id: 'book-002',
      leadId: 'lead-001',
      slot: 'Tomorrow, 10:00 AM',
      owner: 'Alex',
      status: 'reminded',
      recoveryAction: 'SMS reminder sent; DM reminder scheduled at -30m',
    },
    {
      id: 'book-003',
      leadId: 'lead-003',
      slot: 'Yesterday, 11:00 AM',
      owner: 'Alex',
      status: 'recovered',
      recoveryAction: 'Recovered after no-show with one-click rebook',
    },
  ],
  webhookHistory: [
    {
      id: 'wh-001',
      label: 'DM inbound received',
      payload: JSON.stringify(
        {
          event_name: 'Lead',
          source: 'instagram_dm',
          trigger: 'pricing_keyword',
          lead_handle: '@miamoves',
        },
        null,
        2,
      ),
    },
    {
      id: 'wh-002',
      label: 'Call marked no-show',
      payload: JSON.stringify(
        {
          booking_status: 'no-show',
          grace_window_minutes: 10,
          next_state: 'recovery',
        },
        null,
        2,
      ),
    },
  ],
  connectorStates: {
    Zapier: {
      status: 'ready',
      lastPing: 'just now',
      runs: 0,
      note: 'Zapier is staged for the next relay.',
    },
    Make: {
      status: 'ready',
      lastPing: 'just now',
      runs: 0,
      note: 'Make is staged for the next relay.',
    },
    'Meta CAPI': {
      status: 'ready',
      lastPing: 'just now',
      runs: 0,
      note: 'Meta CAPI is staged for the next relay.',
    },
    GHL: {
      status: 'ready',
      lastPing: 'just now',
      runs: 0,
      note: 'GHL is staged for the next relay.',
    },
    Stripe: {
      status: 'ready',
      lastPing: 'just now',
      runs: 0,
      note: 'Stripe is staged for the next relay.',
    },
    Slack: {
      status: 'ready',
      lastPing: 'just now',
      runs: 0,
      note: 'Slack is staged for the next relay.',
    },
    'Google Sheets': {
      status: 'ready',
      lastPing: 'just now',
      runs: 0,
      note: 'Google Sheets is staged for the next relay.',
    },
  },
  deliveryQueue: [
    {
      id: 'dq-001',
      connector: 'Stripe',
      channel: 'checkout_handoff',
      target: '@miamoves',
      payloadLabel: 'InitiateCheckout',
      status: 'delivered',
      lastAttempt: '09:15:11',
      note: 'Low-ticket checkout link delivered after DM qualification.',
    },
    {
      id: 'dq-002',
      connector: 'GHL',
      channel: 'consult_routing',
      target: '@evanbuilds',
      payloadLabel: 'BookingCreated',
      status: 'processing',
      lastAttempt: '14:30:02',
      note: 'Consult lead routed to closer and reminder sequence started.',
    },
    {
      id: 'dq-003',
      connector: 'Meta CAPI',
      channel: 'server_events',
      target: '@jadeteaches',
      payloadLabel: 'Purchase',
      status: 'queued',
      lastAttempt: '08:06:49',
      note: 'Purchase payload normalized and waiting for the next relay window.',
    },
  ],
  operatorNotesHistory: [],
  auditEvents: [
    {
      id: 'aud-001',
      kind: 'webhook',
      title: 'Webhook validated',
      detail: 'Stripe checkout event passed schema checks and was queued for relay.',
      target: 'Stripe',
      timestamp: '09:15:11',
    },
    {
      id: 'aud-002',
      kind: 'rule',
      title: 'Rule test passed',
      detail: 'Keyword trigger matched the hot DM transcript and queued the checkout branch.',
      target: 'rule-001',
      timestamp: '09:16:02',
    },
    {
      id: 'aud-003',
      kind: 'connector',
      title: 'Meta CAPI connector ready',
      detail: 'Server-event naming and match keys are ready for the next export.',
      target: 'Meta CAPI',
      timestamp: '09:17:44',
    },
  ],
}
