export const seedState = {
  leadRecords: [
    {
      id: 'lead-001',
      name: 'Mia Torres',
      handle: '@miamoves',
      source: 'IG DM comment keyword',
      offer: 'Low-ticket challenge',
      stage: 'checkout-sent',
      owner: 'Alex',
      tags: ['dm-sprint', 'warm', 'challenge'],
      budget: '$49 low-ticket',
      nextAction: 'Wait 2h, then send urgency follow-up',
      lastTouch: '2 min ago',
    },
    {
      id: 'lead-002',
      name: 'Evan Ross',
      handle: '@evanbuilds',
      source: 'Story reply',
      offer: 'Consult call',
      stage: 'no-show',
      owner: 'Nina',
      tags: ['consult', 'no-show', 'high-intent'],
      budget: '$2.5k consult',
      nextAction: 'Send recovery voice note + reschedule link',
      lastTouch: '17 min ago',
    },
    {
      id: 'lead-003',
      name: 'Jade Porter',
      handle: '@jadeteaches',
      source: 'Lead form retargeting',
      offer: 'Subscription',
      stage: 'won',
      owner: 'Alex',
      tags: ['subscriber', 'upsell-ready'],
      budget: '$97 monthly',
      nextAction: 'Trigger onboarding autopilot',
      lastTouch: '31 min ago',
    },
    {
      id: 'lead-004',
      name: 'Carlos Vega',
      handle: '@coachcarlos',
      source: 'Instagram DM',
      offer: 'High-ticket consult',
      stage: 'booked',
      owner: 'Nina',
      tags: ['consult', 'booked', 'closer-assigned'],
      budget: '$3k consult',
      nextAction: 'Confirm attendance and preload proof stack before the call.',
      lastTouch: '9 min ago',
    },
    {
      id: 'lead-005',
      name: 'Sienna Blake',
      handle: '@siennastudio',
      source: 'Story reply',
      offer: 'Creator OS subscription',
      stage: 'engaged',
      owner: 'Alex',
      tags: ['subscription', 'warm', 'proof-requested'],
      budget: '$97 monthly',
      nextAction: 'Send testimonial proof and checkout nudge.',
      lastTouch: '6 min ago',
    },
    {
      id: 'lead-006',
      name: 'Noah Kim',
      handle: '@noahlaunches',
      source: 'Lead form retargeting',
      offer: 'Launch sprint',
      stage: 'recovery',
      owner: 'Maya',
      tags: ['no-show', 'recovery', 'priority'],
      budget: '$1.5k sprint',
      nextAction: 'Retry recovery branch and send Slack alert if no response in 30 minutes.',
      lastTouch: '4 min ago',
    },
  ],
  bookingRecords: [
    {
      id: 'book-001',
      leadId: 'lead-002',
      slot: 'Today, 2:30 PM',
      owner: 'Nina',
      status: 'no-show',
      recoveryAction: 'Voice note + reschedule link queued for 15 min delay',
    },
    {
      id: 'book-002',
      leadId: 'lead-001',
      slot: 'Tomorrow, 10:00 AM',
      owner: 'Alex',
      status: 'reminded',
      recoveryAction: 'SMS reminder sent; DM reminder scheduled at -30m',
    },
    {
      id: 'book-003',
      leadId: 'lead-003',
      slot: 'Yesterday, 11:00 AM',
      owner: 'Alex',
      status: 'recovered',
      recoveryAction: 'Recovered after no-show with one-click rebook',
    },
    {
      id: 'book-004',
      leadId: 'lead-004',
      slot: 'Today, 4:00 PM',
      owner: 'Nina',
      status: 'booked',
      recoveryAction: 'Attendance reminder queued in GHL and proof stack preloaded.',
    },
    {
      id: 'book-005',
      leadId: 'lead-006',
      slot: 'Yesterday, 3:00 PM',
      owner: 'Maya',
      status: 'no-show',
      recoveryAction: 'Recovery branch staged with Make relay, Slack alert, and reschedule link.',
    },
  ],
  conversationRecords: [
    {
      id: 'conv-001',
      leadId: 'lead-001',
      intent: 'checkout',
      score: 92,
      automationSummary: 'Tagged as dm-sprint + sent Stripe checkout + queued urgency bump.',
    },
    {
      id: 'conv-002',
      leadId: 'lead-002',
      intent: 'call',
      score: 88,
      automationSummary: 'Routed to consult closer + marked no-show + queued recovery branch.',
    },
    {
      id: 'conv-003',
      leadId: 'lead-003',
      intent: 'proof',
      score: 81,
      automationSummary:
        'Payment webhook promoted the lead to subscriber, triggered onboarding autopilot, and logged a CAPI-ready purchase event.',
    },
    {
      id: 'conv-004',
      leadId: 'lead-004',
      intent: 'call',
      score: 90,
      automationSummary: 'Qualified as high-ticket consult, routed to closer, and booked into the GHL mirror.',
    },
    {
      id: 'conv-005',
      leadId: 'lead-005',
      intent: 'proof',
      score: 76,
      automationSummary: 'Requested proof, queued testimonial branch, and kept the subscription offer warm.',
    },
    {
      id: 'conv-006',
      leadId: 'lead-006',
      intent: 'call',
      score: 84,
      automationSummary: 'No-show recovery branch triggered and staged for Make, Slack, and CAPI relay follow-up.',
    },
  ],
  messageRecords: [
    {
      id: 'msg-001',
      conversationId: 'conv-001',
      sender: 'lead',
      text: 'price for the sprint? i want something fast',
      timestamp: '09:14',
    },
    {
      id: 'msg-002',
      conversationId: 'conv-001',
      sender: 'bot',
      text: 'The sprint is $49 and starts today. Want the checkout link or a quick breakdown?',
      timestamp: '09:14',
    },
    {
      id: 'msg-003',
      conversationId: 'conv-001',
      sender: 'lead',
      text: 'send the link',
      timestamp: '09:15',
    },
    {
      id: 'msg-004',
      conversationId: 'conv-001',
      sender: 'bot',
      text: 'Done. I tagged you for the sprint and dropped the Stripe checkout. If you need proof, I can send wins next.',
      timestamp: '09:15',
    },
    {
      id: 'msg-005',
      conversationId: 'conv-002',
      sender: 'lead',
      text: 'can i talk to someone first before i join?',
      timestamp: '08:42',
    },
    {
      id: 'msg-006',
      conversationId: 'conv-002',
      sender: 'bot',
      text: 'Yes. I can route you to the closer with the best availability. Are you free this afternoon?',
      timestamp: '08:42',
    },
    {
      id: 'msg-007',
      conversationId: 'conv-002',
      sender: 'lead',
      text: 'yep book me',
      timestamp: '08:43',
    },
    {
      id: 'msg-008',
      conversationId: 'conv-002',
      sender: 'bot',
      text: 'Booked for 2:30 PM. If anything changes I will send the reschedule link here.',
      timestamp: '08:43',
    },
    {
      id: 'msg-009',
      conversationId: 'conv-003',
      sender: 'lead',
      text: 'paid. what happens next?',
      timestamp: '08:05',
    },
    {
      id: 'msg-010',
      conversationId: 'conv-003',
      sender: 'bot',
      text: 'You are in. I created your onboarding checklist, folder links, and kickoff instructions. If you want the community link next, I can drop that too.',
      timestamp: '08:06',
    },
    {
      id: 'msg-011',
      conversationId: 'conv-004',
      sender: 'lead',
      text: 'i want to talk before i commit. do you have a closer available?',
      timestamp: '10:11',
    },
    {
      id: 'msg-012',
      conversationId: 'conv-004',
      sender: 'bot',
      text: 'Yes. I routed you to Nina and locked a 4 PM consult slot. I will keep reminders and proof ready here.',
      timestamp: '10:12',
    },
    {
      id: 'msg-013',
      conversationId: 'conv-005',
      sender: 'lead',
      text: 'can you send wins before i buy the creator os?',
      timestamp: '11:04',
    },
    {
      id: 'msg-014',
      conversationId: 'conv-005',
      sender: 'bot',
      text: 'Absolutely. I queued the proof branch first, then I can send the checkout once you are ready.',
      timestamp: '11:05',
    },
    {
      id: 'msg-015',
      conversationId: 'conv-006',
      sender: 'lead',
      text: 'sorry i missed the call. can i get another slot?',
      timestamp: '12:42',
    },
    {
      id: 'msg-016',
      conversationId: 'conv-006',
      sender: 'bot',
      text: 'Yes. I staged the recovery branch, reschedule link, and closer alert so we can recover this quickly.',
      timestamp: '12:43',
    },
  ],
  webhookHistory: [
    {
      id: 'wh-001',
      label: 'DM inbound received',
      payload: JSON.stringify(
        {
          event_name: 'Lead',
          source: 'instagram_dm',
          trigger: 'pricing_keyword',
          lead_handle: '@miamoves',
        },
        null,
        2,
      ),
    },
    {
      id: 'wh-002',
      label: 'Call marked no-show',
      payload: JSON.stringify(
        {
          booking_status: 'no-show',
          grace_window_minutes: 10,
          next_state: 'recovery',
        },
        null,
        2,
      ),
    },
    {
      id: 'wh-003',
      label: 'Stripe purchase received',
      payload: JSON.stringify(
        {
          event_name: 'Purchase',
          source: 'stripe_webhook',
          value: 97,
          currency: 'USD',
          lead_handle: '@jadeteaches',
        },
        null,
        2,
      ),
    },
    {
      id: 'wh-004',
      label: 'GHL appointment booked',
      payload: JSON.stringify(
        {
          booking_status: 'booked',
          owner: 'Nina',
          lead_handle: '@coachcarlos',
          source: 'ghl_appointment',
        },
        null,
        2,
      ),
    },
  ],
  connectorStates: {
    Zapier: {
      status: 'ready',
      lastPing: '1 min ago',
      runs: 4,
      note: 'Zapier is routing proof-requested leads into the reporting branch.',
    },
    Make: {
      status: 'ready',
      lastPing: '1 min ago',
      runs: 6,
      note: 'Make is handling no-show recovery, onboarding, and delayed follow-up relays.',
    },
    'Meta CAPI': {
      status: 'ready',
      lastPing: 'just now',
      runs: 3,
      note: 'Meta CAPI has purchase and recovery-ready server events waiting for relay.',
    },
    GHL: {
      status: 'ready',
      lastPing: '2 min ago',
      runs: 5,
      note: 'GHL is mirroring booked, no-show, and recovery stages with closer ownership.',
    },
    Stripe: {
      status: 'ready',
      lastPing: 'just now',
      runs: 4,
      note: 'Stripe is creating checkout handoffs and payment-confirmed purchase events.',
    },
    Slack: {
      status: 'ready',
      lastPing: '3 min ago',
      runs: 2,
      note: 'Slack is configured for hot-lead alerts and no-show escalation.',
    },
    'Google Sheets': {
      status: 'ready',
      lastPing: '5 min ago',
      runs: 2,
      note: 'Google Sheets is capturing daily queue and revenue snapshots.',
    },
    Typeform: {
      status: 'processing',
      lastPing: '4 min ago',
      runs: 3,
      note: 'Typeform prequalification forms funnel into the DM sprint workflow.',
    },
    Kajabi: {
      status: 'ready',
      lastPing: '2 min ago',
      runs: 1,
      note: 'Kajabi membership pipeline mirrors revenue events after checkout completion.',
    },
    Skool: {
      status: 'ready',
      lastPing: '3 min ago',
      runs: 1,
      note: 'Skool community access updates flow from the onboarding autopilot.',
    },
    Discord: {
      status: 'ready',
      lastPing: '1 min ago',
      runs: 2,
      note: 'Discord escalations fire for hot leads and recovery alerts.',
    },
    Apify: {
      status: 'syncing',
      lastPing: '6 min ago',
      runs: 1,
      note: 'Apify-style scrapers refresh trending comment pools for intent routing.',
    },
  },
  deliveryQueue: [
    {
      id: 'dq-001',
      connector: 'Stripe',
      channel: 'checkout_handoff',
      target: '@miamoves',
      payloadLabel: 'InitiateCheckout',
      status: 'delivered',
      lastAttempt: '09:15:11',
      note: 'Low-ticket checkout link delivered after DM qualification.',
    },
    {
      id: 'dq-002',
      connector: 'GHL',
      channel: 'consult_routing',
      target: '@evanbuilds',
      payloadLabel: 'BookingCreated',
      status: 'processing',
      lastAttempt: '14:30:02',
      note: 'Consult lead routed to closer and reminder sequence started.',
    },
    {
      id: 'dq-003',
      connector: 'Meta CAPI',
      channel: 'server_events',
      target: '@jadeteaches',
      payloadLabel: 'Purchase',
      status: 'queued',
      lastAttempt: '08:06:49',
      note: 'Purchase payload normalized and waiting for the next relay window.',
    },
    {
      id: 'dq-004',
      connector: 'GHL',
      channel: 'consult_routing',
      target: '@coachcarlos',
      payloadLabel: 'AppointmentConfirmed',
      status: 'delivered',
      lastAttempt: '10:12:08',
      note: 'Closer routing and reminder sequence were delivered into the booking pipeline.',
    },
    {
      id: 'dq-005',
      connector: 'Zapier',
      channel: 'proof_branch',
      target: '@siennastudio',
      payloadLabel: 'SendTestimonials',
      status: 'queued',
      lastAttempt: '11:06:14',
      note: 'Proof branch staged before checkout handoff for the subscription offer.',
    },
    {
      id: 'dq-006',
      connector: 'Make',
      channel: 'recovery_automation',
      target: '@noahlaunches',
      payloadLabel: 'NoShowRecovery',
      status: 'processing',
      lastAttempt: '12:44:02',
      note: 'Recovery workflow is sending the reschedule branch and delayed follow-up sequence.',
    },
    {
      id: 'dq-007',
      connector: 'Slack',
      channel: 'hot_lead_alert',
      target: '@noahlaunches',
      payloadLabel: 'CloserAssist',
      status: 'delivered',
      lastAttempt: '12:44:28',
      note: 'Closer assist alert delivered after repeated no-show risk was detected.',
    },
    {
      id: 'dq-008',
      connector: 'Google Sheets',
      channel: 'daily_ops_snapshot',
      target: 'daily_ops_snapshot',
      payloadLabel: 'RevenueSnapshot',
      status: 'delivered',
      lastAttempt: '07:00:00',
      note: 'Daily queue and revenue snapshot exported for reporting.',
    },
    {
      id: 'dq-009',
      connector: 'Typeform',
      channel: 'form_capture',
      target: 'typeform_flow',
      payloadLabel: 'TypeformLead',
      status: 'processing',
      lastAttempt: '10:05:44',
      note: 'Typeform responses trigger DM routing, owner tagging, and lead creation.',
    },
    {
      id: 'dq-010',
      connector: 'Kajabi',
      channel: 'course_access',
      target: 'kajabi_course',
      payloadLabel: 'CourseProvision',
      status: 'queued',
      lastAttempt: '13:00:00',
      note: 'Kajabi access tokens are queued after payment and onboarding finish.',
    },
    {
      id: 'dq-011',
      connector: 'Skool',
      channel: 'community_invite',
      target: 'skool_room',
      payloadLabel: 'SkoolInvite',
      status: 'queued',
      lastAttempt: '13:05:22',
      note: 'Skool workspace invites wait behind the onboarding autopilot.',
    },
    {
      id: 'dq-012',
      connector: 'Discord',
      channel: 'discord_nudge',
      target: 'discord_server',
      payloadLabel: 'DiscordPulse',
      status: 'processing',
      lastAttempt: '12:50:33',
      note: 'Discord pumps alert the team on hot leads and recovery branches.',
    },
    {
      id: 'dq-013',
      connector: 'Apify',
      channel: 'apify_scrape',
      target: 'apify_agent',
      payloadLabel: 'CommentIntake',
      status: 'queued',
      lastAttempt: '06:15:00',
      note: 'Apify scraper refreshes IG comment sentiment for workflow tagging.',
    },
  ],
  deliveryAttempts: [
    {
      id: 'da-001',
      deliveryId: 'dq-001',
      status: 'delivered',
      detail: 'Stripe handoff accepted and payment link sent.',
      attemptedAt: '2026-04-04T09:15:11.000Z',
    },
    {
      id: 'da-002',
      deliveryId: 'dq-002',
      status: 'processing',
      detail: 'GHL routing accepted and reminder branch started.',
      attemptedAt: '2026-04-04T14:30:02.000Z',
    },
    {
      id: 'da-003',
      deliveryId: 'dq-003',
      status: 'queued',
      detail: 'Meta CAPI purchase relay waiting for send window.',
      attemptedAt: '2026-04-04T08:06:49.000Z',
    },
    {
      id: 'da-004',
      deliveryId: 'dq-004',
      status: 'delivered',
      detail: 'GHL accepted the appointment confirmation and reminder sequence.',
      attemptedAt: '2026-04-04T10:12:08.000Z',
    },
    {
      id: 'da-005',
      deliveryId: 'dq-005',
      status: 'queued',
      detail: 'Zapier proof branch is queued ahead of checkout handoff.',
      attemptedAt: '2026-04-04T11:06:14.000Z',
    },
    {
      id: 'da-006',
      deliveryId: 'dq-006',
      status: 'processing',
      detail: 'Make recovery branch is sending reschedule and proof follow-up actions.',
      attemptedAt: '2026-04-04T12:44:02.000Z',
    },
    {
      id: 'da-007',
      deliveryId: 'dq-007',
      status: 'delivered',
      detail: 'Slack alert delivered to the closer escalation channel.',
      attemptedAt: '2026-04-04T12:44:28.000Z',
    },
    {
      id: 'da-008',
      deliveryId: 'dq-008',
      status: 'delivered',
      detail: 'Google Sheets snapshot row append completed.',
      attemptedAt: '2026-04-04T07:00:00.000Z',
    },
    {
      id: 'da-009',
      deliveryId: 'dq-009',
      status: 'processing',
      detail: 'Typeform webhook triggered DM sprint tagging and dispatch.',
      attemptedAt: '2026-04-04T10:05:44.000Z',
    },
    {
      id: 'da-010',
      deliveryId: 'dq-010',
      status: 'queued',
      detail: 'Kajabi course access set to send after onboarding autopilot completes.',
      attemptedAt: '2026-04-04T13:00:00.000Z',
    },
    {
      id: 'da-011',
      deliveryId: 'dq-011',
      status: 'queued',
      detail: 'Skool invite queued for community workspace following onboarding.',
      attemptedAt: '2026-04-04T13:05:22.000Z',
    },
    {
      id: 'da-012',
      deliveryId: 'dq-012',
      status: 'processing',
      detail: 'Discord alert running as part of the recovery escalation path.',
      attemptedAt: '2026-04-04T12:50:33.000Z',
    },
    {
      id: 'da-013',
      deliveryId: 'dq-013',
      status: 'queued',
      detail: 'Apify comment scrape scheduled to refresh automation triggers.',
      attemptedAt: '2026-04-04T06:15:00.000Z',
    },
  ],
  operatorNotesHistory: [
    {
      id: 'note-001',
      note: 'Evan recovery should branch to Nina first, then escalate to Slack if no reply in 30 min.',
      timestamp: '2026-04-04T14:45:00.000Z',
      scenarioId: 'scenario-002',
      stepLabel: 'Recovery workflow',
    },
  ],
  auditEvents: [
    {
      id: 'aud-001',
      kind: 'webhook',
      title: 'Webhook validated',
      detail: 'Stripe checkout event passed schema checks and was queued for relay.',
      target: 'Stripe',
      timestamp: '09:15:11',
    },
    {
      id: 'aud-002',
      kind: 'rule',
      title: 'Rule test passed',
      detail: 'Keyword trigger matched the hot DM transcript and queued the checkout branch.',
      target: 'rule-001',
      timestamp: '09:16:02',
    },
    {
      id: 'aud-003',
      kind: 'connector',
      title: 'Meta CAPI connector ready',
      detail: 'Server-event naming and match keys are ready for the next export.',
      target: 'Meta CAPI',
      timestamp: '09:17:44',
    },
    {
      id: 'aud-004',
      kind: 'workflow',
      title: 'Consult call booked',
      detail: 'Carlos was routed to Nina and booked through the GHL mirror.',
      target: '@coachcarlos',
      timestamp: '10:12:08',
    },
    {
      id: 'aud-005',
      kind: 'connector',
      title: 'Zapier proof branch queued',
      detail: 'Subscription proof branch queued before checkout for Sienna.',
      target: 'Zapier',
      timestamp: '11:06:14',
    },
    {
      id: 'aud-006',
      kind: 'workflow',
      title: 'Recovery branch staged',
      detail: 'Noah no-show path queued Make recovery, Slack alert, and Meta CAPI recovery event.',
      target: '@noahlaunches',
      timestamp: '12:44:02',
    },
    {
      id: 'aud-007',
      kind: 'connector',
      title: 'Slack alert delivered',
      detail: 'Hot lead escalation reached the closer channel after no-show risk persisted.',
      target: 'Slack',
      timestamp: '12:44:28',
    },
    {
      id: 'aud-008',
      kind: 'connector',
      title: 'Typeform lead captured',
      detail: 'New Typeform prequalification hit the DM sprint funnel.',
      target: 'Typeform',
      timestamp: '10:05:44',
    },
    {
      id: 'aud-009',
      kind: 'connector',
      title: 'Apify scrape refreshed',
      detail: 'Apify scraper refreshed comment sentiment for automation tagging.',
      target: 'Apify',
      timestamp: '06:15:00',
    },
  ],
  liveTestRuns: [
    {
      id: 'ltr-001',
      scenarioId: 'scenario-001',
      scenarioTitle: 'DM Sprint Funnel',
      stepLabel: 'Checkout sent',
      payloadLabel: 'InitiateCheckout',
      connector: 'Stripe',
      status: 'accepted',
      resultMessage: 'Stripe accepted the checkout handoff payload.',
      payload: JSON.stringify(
        {
          event_name: 'InitiateCheckout',
          source: 'instagram_dm',
          lead_handle: '@miamoves',
        },
        null,
        2,
      ),
      createdAt: '2026-04-04T09:15:11.000Z',
    },
    {
      id: 'ltr-002',
      scenarioId: 'scenario-002',
      scenarioTitle: 'No-Show Recovery',
      stepLabel: 'Recovery queued',
      payloadLabel: 'NoShowRecovery',
      connector: 'Make',
      status: 'accepted',
      resultMessage: 'Make accepted the no-show recovery branch payload.',
      payload: JSON.stringify(
        {
          booking_status: 'no-show',
          route: 'recovery',
          lead_handle: '@noahlaunches',
        },
        null,
        2,
      ),
      createdAt: '2026-04-04T12:44:02.000Z',
    },
    {
      id: 'ltr-003',
      scenarioId: 'scenario-001',
      scenarioTitle: 'Apify insight refresh',
      stepLabel: 'Scraper sync',
      payloadLabel: 'CommentIntake',
      connector: 'Apify',
      status: 'accepted',
      resultMessage: 'Apify agent returned trending comment insights.',
      payload: JSON.stringify(
        {
          event_name: 'CommentIntake',
          source: 'apify_scrape',
          mention_count: 12,
          lead_handle: '@miamoves',
        },
        null,
        2,
      ),
      createdAt: '2026-04-04T06:15:00.000Z',
    },
  ],
  ruleTestResults: {
    'rule-001': {
      status: 'pass',
      detail: 'Matched pricing keyword in the DM transcript.',
      timestamp: '2026-04-04T09:16:02.000Z',
    },
    'rule-002': {
      status: 'pass',
      detail: 'Matched consult intent and routed to a closer.',
      timestamp: '2026-04-04T10:12:08.000Z',
    },
  },
  onboardingRuns: [
    {
      id: 'onb-001',
      leadId: 'lead-003',
      status: 'provisioned',
      folderUrl: 'https://drive.google.com/drive/folders/demo-jade',
      sopUrl: 'https://docs.google.com/document/d/demo-jade-sop',
      inviteUrl: 'https://circle.so/invite/demo-jade',
      handoffStates: {
        status: 'provisioned',
        destinations: [
          {
            name: 'Kajabi',
            status: 'ready',
            url: 'https://assets.cobe.local/demo-jade/kajabi',
            note: 'Course access is staged for the next onboarding step.',
          },
          {
            name: 'Skool',
            status: 'ready',
            url: 'https://assets.cobe.local/demo-jade/skool',
            note: 'Community invite is ready to send after provisioning.',
          },
          {
            name: 'Discord',
            status: 'ready',
            url: 'https://assets.cobe.local/demo-jade/discord',
            note: 'Community alert is staged for the internal team.',
          },
        ],
      },
    },
  ],
}
